// Run with Node 20+. Data only: no upstream code is executed.
// Regenerates the pinned, attributed catalog; existing handwritten IDs stay intact.
import {writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
const commit = 'f42f895f914319a844c3e3c2279483cae060ea19';
const base = `https://raw.githubusercontent.com/fitrahive/dua-dhikr/${commit}`;
const dailyCategories = ['sleep','sleep','home','home','food','food','food',
  'prayer','prayer','prayer','prayer','food','home','home','home','protection',
  'travel','travel','travel','home','home','travel','weather','weather','weather',
  'weather','forgiveness','strength','strength','strength','strength','home',
  'home','home','guidance','protection','prayer','family'];
const sections = {'daily-dua':38,'morning-dhikr':19,'evening-dhikr':19,
  'dhikr-after-salah':13,'selected-dua':8};
const fixedCategory = {'morning-dhikr':'morning','evening-dhikr':'evening',
  'dhikr-after-salah':'prayer','selected-dua':'guidance'};
const skipped = [], records = [], byArabic = new Map(), checksums = {};
const normalized = s => s.normalize('NFC').replace(/[\u0610-\u061a\u064b-\u065f\u0670\u06d6-\u06ed\u0640]/g,'').replace(/[أإآٱ]/g,'ا').replace(/[^\p{Letter}]/gu,'');
for (const [section, expected] of Object.entries(sections)) {
  const response = await fetch(`${base}/data/dua-dhikr/${section}/en.json`);
  if (!response.ok) throw new Error(`Download failed: ${section}`);
  const raw = await response.text();
  checksums[section] = createHash('sha256').update(raw).digest('hex');
  const rows = JSON.parse(raw);
  if (rows.length !== expected) throw new Error(`Unexpected count: ${section}`);
  for (const [index, row] of rows.entries()) {
    // Existing Qur'anic supplications already use the canonical local Quran text.
    // The combined ablution entry conflates several formulas; omit pending review.
    // Surah recitations remain in the Quran module, not duplicated in this library.
    const reason = !row.source ? 'Missing reference'
      : section === 'daily-dua' && [10,12,13,21].includes(index) ? 'Combined formula or context needs review'
      : section === 'daily-dua' && index === 37 ? 'Already in Quran catalog'
      : section === 'selected-dua' && [0,3].includes(index) ? 'Already in Quran catalog'
      : ['morning-dhikr','evening-dhikr'].includes(section) && index < 4 ? 'Quran recitation; available in Quran module'
      : section === 'dhikr-after-salah' && index >= 8 && index <= 11 ? 'Quran recitation; available in Quran module' : null;
    if (reason) { skipped.push({section,index,reason}); continue; }
    for (const key of ['title','arabic','translation','source']) {
      if (typeof row[key] !== 'string' || !row[key].trim()) throw new Error(`Invalid ${key}`);
    }
    const category = section === 'daily-dua' ? dailyCategories[index] : fixedCategory[section];
    const identity = normalized(row.arabic);
    const existing = byArabic.get(identity);
    if (existing) {
      if (!existing.categories.includes(category)) existing.categories.push(category);
      existing.aliases.push(row.title);
      existing.references.add(row.source);
      continue;
    }
    let title = row.title.trim().replace(/^(Supplication |Dua |Prayer )/,'');
    title = title.charAt(0).toUpperCase() + title.slice(1);
    if (/100 Times/i.test(title)) title = 'Seeking forgiveness and returning to Allah';
    if (/Protected from All Dangers/i.test(title)) title = 'Seeking Allah’s protection';
    const item = {id:`fitrahive-${section}-${index+1}`,category,title,
      categories:[category],aliases:[row.title],arabic:row.arabic,meaning:row.translation,
      references:new Set([row.source]),
      url:`https://github.com/fitrahive/dua-dhikr/blob/${commit}/data/dua-dhikr/${section}/en.json`};
    records.push(item); byArabic.set(identity,item);
  }
}
const quote = s => JSON.stringify(s).replaceAll('$','\\$');
const entries = records.map(r => `  DuaEntry.text(\n    id: ${quote(r.id)}, category: ${quote(r.category)},\n    title: ${quote(r.title)}, keywords: ${quote(r.categories.join(' '))},\n    aliases: ${quote(r.aliases.join(' '))},\n    additionalCategories: [${r.categories.slice(1).map(quote).join(', ')}],\n    text: ${quote(r.arabic)},\n    meaning: ${quote(r.meaning)},\n    collectionReference: ${quote([...r.references].join(' • '))},\n    collectionUrl: ${quote(r.url)},\n  ),`).join('\n');
writeFileSync('lib/core/dua/dua_imported.dart', `// Generated by tool/import_duas.mjs. MIT © 2023 Fitrahive.\n// Pinned source ${commit}; see assets/licenses/fitrahive-dua-dhikr.txt.\npart of 'dua_catalog.dart';\n\nconst _importedDuas = <DuaEntry>[\n${entries}\n];\n`);
const license = await fetch(`${base}/LICENSE`);
if (!license.ok) throw new Error('License download failed');
writeFileSync('assets/licenses/fitrahive-dua-dhikr.txt', await license.text());
writeFileSync('docs/dua-import-manifest.json', JSON.stringify({commit,checksums,imported:records.length,skipped},null,2)+'\n');
console.log(`Imported ${records.length} unique texts; excluded ${skipped.length} entries; retained cross-category membership.`);
